include = [
    "../methods/mean_flow.toml",
    "../models/mlp_flow.toml",
    "../datasets/dino.toml",
]

[mean_flow]
nfe = 1
implicit_forward = true
stopgrad = false

# Any combo-specific overrides...
[train]
lr = 5e-4
iterations = 40_000
batch_size = 4096
