entrypoint = "gnx.main.diffusion:train"

[train]
optimizer = "adam"
lr = 1e-3
lr_schedule = "constant"
iterations = 20000
batch_size = 256

[diffusion]
nfe = 32
integrator = "euler"

[diffusion.train_schedule]
type = "none" # use the eval schedule for training

[diffusion.eval_schedule]
type = "log_linear_noise"
log_linear_noise.min_sigma = 0.01
log_linear_noise.max_sigma = 35
