entrypoint = "gnx.main.distilled_flow:train"

[distilled_flow]
nfe = 1
# must be at least train.batch_size

[distilled_flow.train_schedule]
type = "none" # use the eval schedule for training

[distilled_flow.eval_schedule]
type = "log_linear"
log_linear.min_sigma = 0.01
log_linear.max_sigma = 35

[train]
batch_size = 1024
iterations = 20_000
lr = 5e-4
