entrypoint = "gnx.main.sinkhorn_flow:train"

[sinkhorn_flow]
nfe = 1
# must be at least train.batch_size
discrete_times = true
ot_batch_size = 5000
ot_batches = 1
rel_epsilon = 0.01

[train]
batch_size = 1024
#
iterations = 20000
lr = 5e-4
